/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package posproject1;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.TimeZone;
import javax.swing.JOptionPane;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.TableModel;
import com.google.zxing.BarcodeFormat;
import com.google.zxing.WriterException;
import com.google.zxing.common.BitMatrix;
import com.google.zxing.qrcode.QRCodeWriter;
import java.awt.image.BufferedImage;
import java.sql.ResultSet;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.Timer;

/**
 *
 * @author jo
 */
public class POSFrame extends javax.swing.JFrame {
    
    ArrayList<Barang> daftarBarang;

    
    TableModel daftarModel;
    boolean beliToken = false;
    int jumlahBelanja = 0;
    
     /**
     * Creates new form POSFrame
     */
    public POSFrame() { 
        
        DBConnector.initDBConnection();
        
        Barang.loadBarangFromDB();
        Makanan.loadBarangFromDB();
        Pulsa.loadBarangFromDB();
        Token.loadBarangFromDB();
        System.out.println(Barang.daftarBarang.size());
        
        daftarBarang = Barang.daftarBarang;
        
        Timer timer = new Timer(1000, e -> {
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd ");
            DateTimeFormatter formats = DateTimeFormatter.ofPattern("hh:mm:ss");

            LocalDateTime now = LocalDateTime.now();
            String formattedDate = now.format(formatter);
            String formatsDate = now.format(formats);
            waktuTextField.setText(formattedDate);
            timeTextField.setText(formatsDate);
        });
        timer.start();
        
        initComponents();
        
        daftarModel = daftarTable.getModel();
        daftarModel.addTableModelListener(new TableModelListener() {
            @Override
            
            public void tableChanged(TableModelEvent tme) {
                
                if (tme.getColumn() == 7)
                {
                    
                    int baris = tme.getFirstRow();
                    int kolom = tme.getColumn();
                    
                    float harga =  (float)daftarModel.getValueAt(baris, 5);
                    int jumlah = (int)daftarModel.getValueAt(baris,7);
                    float total = harga*jumlah;
                    daftarModel.setValueAt(total, baris, 8);
                    
                float totalBelanja = 0.0f;
                total = 0.0f;
                
                //WARNING jumlahBelanja ini belum update ketika listener ini dipanggil
                for (int i=0; i<jumlahBelanja;i++){
                    total =  (float)daftarModel.getValueAt(i, 8);
                    totalBelanja =  totalBelanja + total;
                }
                int totalBelanjaInt =(int)totalBelanja;
                totalBelanjaTextField.setText(String.format("%,d",totalBelanjaInt));
                }
                
            }
        
            
        });
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        kodeTextField = new javax.swing.JTextField();
        hargaTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        daftarTable = new javax.swing.JTable();
        namaTextField = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        totalBelanjaTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        resetButton = new javax.swing.JButton();
        pilihPembayaranButton = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        noTelpTextField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        barangTextField = new javax.swing.JTextField();
        noMeteranTextField = new javax.swing.JTextField();
        pilihPembayaranTabbedPane = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        kasirIDTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        waktuTextField = new javax.swing.JTextField();
        timeTextField = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        tunaiButton = new javax.swing.JButton();
        kartuDebitButton = new javax.swing.JButton();
        qrisButton = new javax.swing.JButton();
        totalBelanjaLabel = new javax.swing.JLabel();
        totalTextField = new javax.swing.JTextField();
        pembayaranTabbedPane = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        tunaiPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        payTunai = new javax.swing.JButton();
        dibayarTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        kembalianTextField = new javax.swing.JTextField();
        tunaiLabel = new javax.swing.JLabel();
        qrisPanel = new javax.swing.JPanel();
        qrisLabel = new javax.swing.JLabel();
        qrLabel = new javax.swing.JLabel();
        nmidTextField = new javax.swing.JTextField();
        payQris = new javax.swing.JButton();
        kartuDebitPanel = new javax.swing.JPanel();
        noCardTextField = new javax.swing.JTextField();
        BankNamaCbx = new javax.swing.JComboBox<>();
        Bank = new javax.swing.JLabel();
        Nokartu = new javax.swing.JLabel();
        payDebit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Toko RAJYM");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/posproject1/shop.png")).getImage());
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 204, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Barang");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Harga");

        kodeTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        kodeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kodeTextFieldActionPerformed(evt);
            }
        });

        hargaTextField.setEditable(false);
        hargaTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        daftarTable.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        daftarTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "No", "Kode", "Nama", "Operator", "Kadaluarsa", "Harga Satuan", "Nominal", "Jumlah", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.Float.class, java.lang.Integer.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(daftarTable);
        if (daftarTable.getColumnModel().getColumnCount() > 0) {
            daftarTable.getColumnModel().getColumn(0).setResizable(false);
            daftarTable.getColumnModel().getColumn(0).setPreferredWidth(20);
            daftarTable.getColumnModel().getColumn(1).setResizable(false);
            daftarTable.getColumnModel().getColumn(1).setPreferredWidth(40);
            daftarTable.getColumnModel().getColumn(2).setResizable(false);
            daftarTable.getColumnModel().getColumn(2).setPreferredWidth(100);
            daftarTable.getColumnModel().getColumn(3).setResizable(false);
            daftarTable.getColumnModel().getColumn(4).setResizable(false);
            daftarTable.getColumnModel().getColumn(4).setPreferredWidth(120);
            daftarTable.getColumnModel().getColumn(5).setResizable(false);
            daftarTable.getColumnModel().getColumn(5).setPreferredWidth(70);
            daftarTable.getColumnModel().getColumn(7).setResizable(false);
            daftarTable.getColumnModel().getColumn(7).setPreferredWidth(40);
            daftarTable.getColumnModel().getColumn(8).setResizable(false);
            daftarTable.getColumnModel().getColumn(8).setPreferredWidth(70);
        }

        namaTextField.setEditable(false);
        namaTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        totalBelanjaTextField.setEditable(false);
        totalBelanjaTextField.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Total Belanja");

        resetButton.setBackground(new java.awt.Color(102, 204, 255));
        resetButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 24)); // NOI18N
        resetButton.setText("Reset");
        resetButton.setBorder(null);
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });

        pilihPembayaranButton.setBackground(new java.awt.Color(235, 37, 116));
        pilihPembayaranButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 24)); // NOI18N
        pilihPembayaranButton.setForeground(new java.awt.Color(255, 255, 255));
        pilihPembayaranButton.setText("Pilih Pembayaran");
        pilihPembayaranButton.setBorder(null);
        pilihPembayaranButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilihPembayaranButtonActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setText("Code");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("No Telp");

        noTelpTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noTelpTextFieldActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel11.setText("No Meteran");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel12.setText("Nama");

        barangTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        barangTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barangTextFieldActionPerformed(evt);
            }
        });

        noMeteranTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noMeteranTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jSeparator3)
                                .addGap(344, 344, 344))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(59, 59, 59)
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(namaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(hargaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(noTelpTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel11))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(barangTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(72, 72, 72)
                                                .addComponent(jLabel10)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(kodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(noMeteranTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addGap(69, 69, 69))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 770, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(resetButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(totalBelanjaTextField)
                                    .addComponent(pilihPembayaranButton, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE))))))
                .addGap(42, 42, 42))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(kodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(barangTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(noTelpTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(noMeteranTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(namaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(hargaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalBelanjaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pilihPembayaranButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(108, 108, 108))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -1, 850, 720));

        jPanel2.setBackground(new java.awt.Color(102, 204, 255));

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/posproject1/shop.png"))); // NOI18N

        jLabel9.setFont(new java.awt.Font("Segoe UI Black", 0, 48)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("TOKO RAJYM");

        kasirIDTextField.setEditable(false);
        kasirIDTextField.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        kasirIDTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kasirIDTextFieldActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("ID");

        waktuTextField.setEditable(false);
        waktuTextField.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        waktuTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        waktuTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                waktuTextFieldActionPerformed(evt);
            }
        });

        timeTextField.setEditable(false);
        timeTextField.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        timeTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        timeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timeTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE)
                .addGap(9, 9, 9)
                .addComponent(jLabel8)
                .addGap(83, 83, 83))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(kasirIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(timeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(98, 98, 98))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(59, 59, 59)
                    .addComponent(waktuTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(267, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kasirIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(timeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(152, Short.MAX_VALUE)
                    .addComponent(waktuTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        pilihPembayaranTabbedPane.addTab("tab1", jPanel2);

        jPanel3.setBackground(new java.awt.Color(102, 204, 255));

        tunaiButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tunaiButton.setText("Tunai");
        tunaiButton.setMaximumSize(new java.awt.Dimension(72, 33));
        tunaiButton.setMinimumSize(new java.awt.Dimension(72, 33));
        tunaiButton.setPreferredSize(new java.awt.Dimension(72, 33));
        tunaiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tunaiButtonActionPerformed(evt);
            }
        });

        kartuDebitButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        kartuDebitButton.setText("Kartu Debit");
        kartuDebitButton.setMaximumSize(new java.awt.Dimension(100, 33));
        kartuDebitButton.setMinimumSize(new java.awt.Dimension(100, 33));
        kartuDebitButton.setPreferredSize(new java.awt.Dimension(100, 33));
        kartuDebitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kartuDebitButtonActionPerformed(evt);
            }
        });

        qrisButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/posproject1/gambar/QRIS.png"))); // NOI18N
        qrisButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qrisButtonActionPerformed(evt);
            }
        });

        totalBelanjaLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        totalBelanjaLabel.setText("Total Belanja");

        totalTextField.setEditable(false);
        totalTextField.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        totalTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(totalBelanjaLabel)
                .addGap(220, 220, 220))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(tunaiButton, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(kartuDebitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(qrisButton))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addComponent(totalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(81, 81, 81))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tunaiButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(qrisButton)
                    .addComponent(kartuDebitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(totalBelanjaLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(totalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        pilihPembayaranTabbedPane.addTab("tab2", jPanel3);

        getContentPane().add(pilihPembayaranTabbedPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(846, -44, 520, 230));

        jPanel4.setBackground(new java.awt.Color(102, 204, 255));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 520, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 539, Short.MAX_VALUE)
        );

        pembayaranTabbedPane.addTab("tab1", jPanel4);

        tunaiPanel.setBackground(new java.awt.Color(102, 204, 255));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Jumlah yang Dibayar");

        payTunai.setBackground(new java.awt.Color(235, 37, 116));
        payTunai.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        payTunai.setForeground(new java.awt.Color(255, 255, 255));
        payTunai.setText("Pay Now");
        payTunai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payTunaiActionPerformed(evt);
            }
        });

        dibayarTextField.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        dibayarTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dibayarTextFieldActionPerformed(evt);
            }
        });
        dibayarTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                dibayarTextFieldKeyReleased(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Kembalian");

        kembalianTextField.setEditable(false);
        kembalianTextField.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N

        tunaiLabel.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        tunaiLabel.setText("Tunai");

        javax.swing.GroupLayout tunaiPanelLayout = new javax.swing.GroupLayout(tunaiPanel);
        tunaiPanel.setLayout(tunaiPanelLayout);
        tunaiPanelLayout.setHorizontalGroup(
            tunaiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tunaiPanelLayout.createSequentialGroup()
                .addGroup(tunaiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tunaiPanelLayout.createSequentialGroup()
                        .addGap(194, 194, 194)
                        .addComponent(jLabel6))
                    .addGroup(tunaiPanelLayout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addGroup(tunaiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dibayarTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kembalianTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(tunaiPanelLayout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(jLabel4))
                    .addGroup(tunaiPanelLayout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addComponent(tunaiLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(tunaiPanelLayout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(payTunai, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(158, Short.MAX_VALUE))
        );
        tunaiPanelLayout.setVerticalGroup(
            tunaiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tunaiPanelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(tunaiLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dibayarTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kembalianTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(payTunai)
                .addContainerGap(210, Short.MAX_VALUE))
        );

        pembayaranTabbedPane.addTab("tab2", tunaiPanel);

        qrisPanel.setBackground(new java.awt.Color(102, 204, 255));

        qrisLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/posproject1/gambar/QRIS.png"))); // NOI18N

        qrLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        qrLabel.setMinimumSize(new java.awt.Dimension(200, 200));

        nmidTextField.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        nmidTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        payQris.setBackground(new java.awt.Color(235, 37, 116));
        payQris.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        payQris.setForeground(new java.awt.Color(255, 255, 255));
        payQris.setText("Pay Now");
        payQris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payQrisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout qrisPanelLayout = new javax.swing.GroupLayout(qrisPanel);
        qrisPanel.setLayout(qrisPanelLayout);
        qrisPanelLayout.setHorizontalGroup(
            qrisPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, qrisPanelLayout.createSequentialGroup()
                .addGap(0, 178, Short.MAX_VALUE)
                .addComponent(nmidTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(192, 192, 192))
            .addGroup(qrisPanelLayout.createSequentialGroup()
                .addGroup(qrisPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(qrisPanelLayout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(qrLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(qrisPanelLayout.createSequentialGroup()
                        .addGap(225, 225, 225)
                        .addComponent(qrisLabel))
                    .addGroup(qrisPanelLayout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(payQris, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        qrisPanelLayout.setVerticalGroup(
            qrisPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(qrisPanelLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(qrisLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(qrLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nmidTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(payQris)
                .addContainerGap(170, Short.MAX_VALUE))
        );

        pembayaranTabbedPane.addTab("tab1", qrisPanel);

        kartuDebitPanel.setBackground(new java.awt.Color(102, 204, 255));

        noCardTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        noCardTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noCardTextFieldActionPerformed(evt);
            }
        });

        BankNamaCbx.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        BankNamaCbx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        Bank.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Bank.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Bank.setText("Bank");

        Nokartu.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Nokartu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Nokartu.setText("No Kartu");

        payDebit.setBackground(new java.awt.Color(235, 37, 116));
        payDebit.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        payDebit.setForeground(new java.awt.Color(255, 255, 255));
        payDebit.setText("Pay Now");
        payDebit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payDebitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout kartuDebitPanelLayout = new javax.swing.GroupLayout(kartuDebitPanel);
        kartuDebitPanel.setLayout(kartuDebitPanelLayout);
        kartuDebitPanelLayout.setHorizontalGroup(
            kartuDebitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kartuDebitPanelLayout.createSequentialGroup()
                .addContainerGap(157, Short.MAX_VALUE)
                .addGroup(kartuDebitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kartuDebitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(BankNamaCbx, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(kartuDebitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kartuDebitPanelLayout.createSequentialGroup()
                                .addComponent(noCardTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(152, 152, 152))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kartuDebitPanelLayout.createSequentialGroup()
                                .addComponent(Bank, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(208, 208, 208))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kartuDebitPanelLayout.createSequentialGroup()
                        .addComponent(payDebit, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(169, 169, 169))))
            .addGroup(kartuDebitPanelLayout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addComponent(Nokartu, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        kartuDebitPanelLayout.setVerticalGroup(
            kartuDebitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kartuDebitPanelLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(Bank)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BankNamaCbx, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Nokartu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(noCardTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(payDebit)
                .addContainerGap(203, Short.MAX_VALUE))
        );

        pembayaranTabbedPane.addTab("tab3", kartuDebitPanel);

        getContentPane().add(pembayaranTabbedPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 150, 520, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kodeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
        String kodeInput = kodeTextField.getText();
        String barang = barangTextField.getText();
        String barangBesar = barang.toUpperCase();
        
        if(kodeInput.isEmpty()){
            JOptionPane.showMessageDialog(null, "Kode barang kosong");
        } else if (barangBesar.equals("MAKANAN")) 
        {
            isiTable();
        }
    }
                          

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
       new POSFrame().setVisible(true);
       dispose();
         
    }//GEN-LAST:event_resetButtonActionPerformed

    private void pilihPembayaranButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilihPembayaranButtonActionPerformed
        // TODO add your handling code here:
        pilihPembayaranTabbedPane.setSelectedIndex(1);
        String totalBelanjaString = totalBelanjaTextField.getText();
        totalBelanjaString = totalBelanjaString.replace(",","");
        int totalBelanjaInt = Integer.valueOf(totalBelanjaString);
        totalTextField.setText(String.format("%,d",totalBelanjaInt));
        
    }//GEN-LAST:event_pilihPembayaranButtonActionPerformed

    private void tunaiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tunaiButtonActionPerformed
        // TODO add your handling code here:
        pembayaranTabbedPane.setSelectedIndex(1);
    }//GEN-LAST:event_tunaiButtonActionPerformed

    private void qrisButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qrisButtonActionPerformed
        // TODO add your handling code here:
        pembayaranTabbedPane.setSelectedIndex(2);
        //Data pembayaran QRIS
        generateQRCode();
    }//GEN-LAST:event_qrisButtonActionPerformed

    private void dibayarTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dibayarTextFieldActionPerformed
        // TODO add your handling code here:
        String totalBelanjaString = totalBelanjaTextField.getText();
        totalBelanjaString = totalBelanjaString.replace(",","");
        int totalBelanjaInt = Integer.valueOf(totalBelanjaString);
        float totalBelanjaFloat = Float.valueOf(totalBelanjaInt);
        
        String dibayarString = dibayarTextField.getText();
        dibayarString = dibayarString.replace(",","");
        int dibayarInt = Integer.valueOf(dibayarString);
        
        if(dibayarInt<totalBelanjaInt){
            JOptionPane.showMessageDialog(null, "Jumlah yang dibayar kurang dari total harga");
        }else{

        int kembalianInt = dibayarInt - totalBelanjaInt;
        float kembalianFloat = Float.valueOf(kembalianInt);
        
        kembalianTextField.setText(String.format("%,d",kembalianInt));
        }
    }//GEN-LAST:event_dibayarTextFieldActionPerformed

    private void dibayarTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dibayarTextFieldKeyReleased
        // TODO add your handling code here:
        String dibayarString = dibayarTextField.getText();
        dibayarString =dibayarString.replace(",","");
        int dibayarInput = Integer.valueOf(dibayarString);
        dibayarTextField.setText(String.format("%,d",dibayarInput));
    }//GEN-LAST:event_dibayarTextFieldKeyReleased

    private void kartuDebitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kartuDebitButtonActionPerformed
        // TODO add your handling code here:
        pembayaranTabbedPane.setSelectedIndex(3);
        
    }//GEN-LAST:event_kartuDebitButtonActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        //codebox pada agama
        BankNamaCbx.removeAllItems();
        BankNamaCbx.addItem("Select");
        BankNamaCbx.addItem("BRI");
        BankNamaCbx.addItem("BNI");
        BankNamaCbx.addItem("Mandiri");
        BankNamaCbx.addItem("BCA");
        BankNamaCbx.addItem("BTN");
        BankNamaCbx.addItem("BSI");
        
        kodetransaksi();
        
        
    }//GEN-LAST:event_formWindowActivated

    private void noCardTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noCardTextFieldActionPerformed
        // TODO add your handling code here:
        
        String NoCardString=noCardTextField.getText();
        int a=NoCardString.length();
        try {
            Integer.valueOf(NoCardString);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Anda harus mengisi No Kartu");
        }
    }//GEN-LAST:event_noCardTextFieldActionPerformed

    private void payQrisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payQrisActionPerformed
        // TODO add your handling code here:
        QRCode qris = new QRCode();
        
        String totalHargaString = totalTextField.getText();
        totalHargaString = totalHargaString.replace(",", "");
        float totalHargaFloat = Float.parseFloat(totalHargaString);
        qris.setTotalHarga(totalHargaFloat);
        
        String waktuPembayaran = waktuTextField.getText();
        qris.setWaktuPembayaran(waktuPembayaran);
        
        String IDPembayaran = kasirIDTextField.getText();
        String formattedOutput = IDPembayaran.substring(4);
        int result = Integer.parseInt(formattedOutput);
        qris.setIDPembayaran(result);
        
        try {
            qris.simpanDatabase();
        } catch (SQLException ex) {
            Logger.getLogger(Pembayaran.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        if(beliToken){
          generateToken();
        }else{
            JOptionPane.showMessageDialog(null, "Payment Successful!!!");
        }
        
    }//GEN-LAST:event_payQrisActionPerformed

    private void noTelpTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noTelpTextFieldActionPerformed
        String kodeInput = kodeTextField.getText();
        String barang = barangTextField.getText();
        String barangBesar = barang.toUpperCase();
        
        if(kodeInput.isEmpty()){
            JOptionPane.showMessageDialog(null, "Kode barang kosong");
        } else if (barangBesar.equals("PULSA")) 
        {
            isiTable();
        }
    }//GEN-LAST:event_noTelpTextFieldActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        setExtendedState(POSFrame.MAXIMIZED_BOTH);
    }//GEN-LAST:event_formWindowOpened

    private void barangTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barangTextFieldActionPerformed
        String barang = barangTextField.getText();
        String barangBesar = barang.toUpperCase();
        if (barangBesar.equals("MAKANAN")) {
            kodeTextField.setText("MKN");
        } else if (barangBesar.equals("PULSA")) {
            kodeTextField.setText("PL");
        } else if (barangBesar.equals("TOKEN")) {
            kodeTextField.setText("TKN");
        }else {
           JOptionPane.showMessageDialog(null, "Barang tidak tersedia");
        }
    }//GEN-LAST:event_barangTextFieldActionPerformed

    private void noMeteranTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noMeteranTextFieldActionPerformed
        
        String kodeInput = kodeTextField.getText();
        String barang = barangTextField.getText();
        String barangBesar = barang.toUpperCase();
        
        if(kodeInput.isEmpty()){
            JOptionPane.showMessageDialog(null, "Kode barang kosong");
        } else if (barangBesar.equals("TOKEN")) 
        {
            isiTable();
            beliToken = true;
        }
        
    }//GEN-LAST:event_noMeteranTextFieldActionPerformed

    private void kasirIDTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kasirIDTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kasirIDTextFieldActionPerformed

    private void payTunaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payTunaiActionPerformed
        // TODO add your handling code here:
        
        String totalBelanjaString = totalTextField.getText();
        totalBelanjaString = totalBelanjaString.replace(",","");
        float totalBelanjaFloat = Float.valueOf(totalBelanjaString);
        
        String dibayarString = dibayarTextField.getText();
        dibayarString = dibayarString.replace(",","");
        int dibayarInt = Integer.valueOf(dibayarString);
        float dibayarFloat = Float.valueOf(dibayarInt);
       
        float kembalianFloat = dibayarFloat-totalBelanjaFloat;
        
        Tunai kas = new Tunai(kembalianFloat, totalBelanjaFloat);
        
        String waktuPembayaran = waktuTextField.getText();
        kas.setWaktuPembayaran(waktuPembayaran);
        String IDPembayaran = kasirIDTextField.getText();
        String formattedOutput = IDPembayaran.substring(4);
        int result = Integer.parseInt(formattedOutput);
        kas.setIDPembayaran(result);
        
        try {
            kas.simpanDatabase();
        } catch (SQLException ex) {
            Logger.getLogger(Pembayaran.class.getName()).log(Level.SEVERE, null, ex);
        }
        if(beliToken){
          generateToken();
        }else{
            JOptionPane.showMessageDialog(null, "Payment Successful!!!");
        }
        
        
    }//GEN-LAST:event_payTunaiActionPerformed

    private void payDebitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payDebitActionPerformed
        // TODO add your handling code here:
        String BankNama = BankNamaCbx.getSelectedItem().toString();   
        String NoCard = noCardTextField.getText();
        KartuDebit debit = new KartuDebit(BankNama,NoCard);
        
        String totalHargaString = totalTextField.getText();
        totalHargaString = totalHargaString.replace(",", "");
        float totalHargaFloat = Float.parseFloat(totalHargaString);
        debit.setTotalHarga(totalHargaFloat);
        
        String waktuPembayaran = waktuTextField.getText();
        debit.setWaktuPembayaran(waktuPembayaran);
        
        String IDPembayaran = kasirIDTextField.getText();
        String formattedOutput = IDPembayaran.substring(4);
        int result = Integer.parseInt(formattedOutput);
        debit.setIDPembayaran(result);
        
        try {
            debit.simpanDatabase();
        } catch (SQLException ex) {
            Logger.getLogger(Pembayaran.class.getName()).log(Level.SEVERE, null, ex);
        }
        if(beliToken){
          generateToken();
        }else{
            JOptionPane.showMessageDialog(null, "Payment Successful!!!");
        }
        
        
    }//GEN-LAST:event_payDebitActionPerformed

    private void waktuTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_waktuTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_waktuTextFieldActionPerformed

    private void timeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_timeTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(POSFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(POSFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(POSFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(POSFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new POSFrame().setVisible(true);
            }
        });
    }
    
  public void generateQRCode() {
        String konten = "Konten QR Code";
        QRCodeWriter qrCodeWriter = new QRCodeWriter();
        try {
            BitMatrix bitMatrix = qrCodeWriter.encode(konten, BarcodeFormat.QR_CODE, 200, 200);
            BufferedImage qrImage = new BufferedImage(200, 200, BufferedImage.TYPE_INT_RGB);
            for (int x = 0; x < 200; x++) {
                for (int y = 0; y < 200; y++) {
                    qrImage.setRGB(x, y, bitMatrix.get(x, y) ? 0x000000 : 0xFFFFFF);
                }
            }
            ImageIcon qrCodeIcon = new ImageIcon(qrImage);
            qrLabel.setIcon(qrCodeIcon);
        } catch (WriterException e) {
            e.printStackTrace();
        }
    }
  private void isiTable(){
    String kodeInput = kodeTextField.getText();
    Barang tempBarang;
        boolean search = false;
        for (int i = 0; i < daftarBarang.size(); i++)
        {
            tempBarang = daftarBarang.get(i);
            
            //WARNING: tempIndex digunakan untuk index baris 
            //dimulai dari index 0 
            int tempIndex=0;
            if (tempBarang.kode.equals(kodeInput))
            {
                tempIndex = jumlahBelanja;
                jumlahBelanja++;
                
                System.out.println("Barang Ditemukan");
                namaTextField.setText(tempBarang.nama);
                hargaTextField.setText(Float.toString(tempBarang.harga));
                
                
                daftarModel.setValueAt(jumlahBelanja, tempIndex, 0);
                daftarModel.setValueAt(kodeInput, tempIndex, 1);
                daftarModel.setValueAt(tempBarang.nama, tempIndex, 2);
                daftarModel.setValueAt(tempBarang.operator, tempIndex, 3);
                daftarModel.setValueAt(tempBarang.kadaluarsa, tempIndex, 4);
                daftarModel.setValueAt(tempBarang.harga, tempIndex, 5);
                daftarModel.setValueAt(tempBarang.nominal, tempIndex, 6);
                daftarModel.setValueAt(1, tempIndex, 7);
                daftarModel.setValueAt(tempBarang.harga, tempIndex, 8);
                search = true;
                
            }
            }if(!search){
            JOptionPane.showMessageDialog(null, "Kode barang tidak ada");
            }  
}
  public void generateToken(){
        Random rand = new Random(); 
            int angka1 = rand.nextInt(10);
            int angka2 = rand.nextInt(10);
            int angka3 = rand.nextInt(10);
            int angka4 = rand.nextInt(10);
            int angka5 = rand.nextInt(10);
            int angka6 = rand.nextInt(10);
            int angka7 = rand.nextInt(10);
            int angka8 = rand.nextInt(10);
            int angka9 = rand.nextInt(10);
            int angka10 = rand.nextInt(10);
            int angka11 = rand.nextInt(10);
            int angka12 = rand.nextInt(10);
            int angka13 = rand.nextInt(10);
            int angka14 = rand.nextInt(10);
            int angka15 = rand.nextInt(10);
            int angka16 = rand.nextInt(10);
            int angka17 = rand.nextInt(10);
            int angka18 = rand.nextInt(10);
            int angka19 = rand.nextInt(10);
            int angka20 = rand.nextInt(10);
            
        String nomorToken = String.valueOf(angka1)+String.valueOf(angka2)+String.valueOf(angka3)+String.valueOf(angka4)+String.valueOf(angka5)+String.valueOf(angka6)+String.valueOf(angka7)+String.valueOf(angka8)+String.valueOf(angka9)+String.valueOf(angka10)+String.valueOf(angka11)+String.valueOf(angka12)+String.valueOf(angka13)+String.valueOf(angka14)+String.valueOf(angka15)+String.valueOf(angka16)+String.valueOf(angka17)+String.valueOf(angka18)+String.valueOf(angka19)+String.valueOf(angka20);
        JOptionPane.showMessageDialog(this,"Pembayaran berhasil! Nomor Token : " + nomorToken);
    }
  private void kodetransaksi(){
        try {
            Statement stmt = DBConnector.connection.createStatement();
            String sql = "SELECT COUNT(*) as jumlah_pembayaran FROM transaksi";
            ResultSet rs = stmt.executeQuery(sql);
            rs.next();
            int JumlahData = rs.getInt("jumlah_pembayaran");
            System.out.println(JumlahData);
            int idtransaksi = JumlahData+1;
            String idTransString = String.format("ID-%03d", idtransaksi);
            kasirIDTextField.setText(idTransString);
            nmidTextField.setText(idTransString);
        } catch (SQLException ex) {
            Logger.getLogger(POSFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
  }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Bank;
    private javax.swing.JComboBox<String> BankNamaCbx;
    private javax.swing.JLabel Nokartu;
    private javax.swing.JTextField barangTextField;
    private javax.swing.JTable daftarTable;
    private javax.swing.JTextField dibayarTextField;
    private javax.swing.JTextField hargaTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JButton kartuDebitButton;
    private javax.swing.JPanel kartuDebitPanel;
    private javax.swing.JTextField kasirIDTextField;
    private javax.swing.JTextField kembalianTextField;
    private javax.swing.JTextField kodeTextField;
    private javax.swing.JTextField namaTextField;
    private javax.swing.JTextField nmidTextField;
    private javax.swing.JTextField noCardTextField;
    private javax.swing.JTextField noMeteranTextField;
    private javax.swing.JTextField noTelpTextField;
    private javax.swing.JButton payDebit;
    private javax.swing.JButton payQris;
    private javax.swing.JButton payTunai;
    private javax.swing.JTabbedPane pembayaranTabbedPane;
    private javax.swing.JButton pilihPembayaranButton;
    private javax.swing.JTabbedPane pilihPembayaranTabbedPane;
    private javax.swing.JLabel qrLabel;
    private javax.swing.JButton qrisButton;
    private javax.swing.JLabel qrisLabel;
    private javax.swing.JPanel qrisPanel;
    private javax.swing.JButton resetButton;
    private javax.swing.JTextField timeTextField;
    private javax.swing.JLabel totalBelanjaLabel;
    private javax.swing.JTextField totalBelanjaTextField;
    private javax.swing.JTextField totalTextField;
    private javax.swing.JButton tunaiButton;
    private javax.swing.JLabel tunaiLabel;
    private javax.swing.JPanel tunaiPanel;
    private javax.swing.JTextField waktuTextField;
    // End of variables declaration//GEN-END:variables
}
